'use strict';

export default {
    GET_ALL_ITEMS: 'GET_ALL_ITEMS',
    ADD_PHONE_TO_SHOP: 'ADD_PHONE_TO_SHOP',
    REMOVE_PHONE_FROM_SHOP: 'REMOVE_PHONE_FROM_SHOP',
    ADD_COMPUTER_TO_SHOP: 'ADD_COMPUTER_TO_SHOP',
  	REMOVE_COMPUTER_FROM_SHOP: 'REMOVE_COMPUTER_FROM_SHOP'
};
